FROM node:18-alpine
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production
COPY . .
# No need to expose port here if using docker-compose,
# but good practice if running standalone
# EXPOSE 5001
CMD ["node", "server.js"]